#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build idioms_pre2.json from curated multi-source research.
Sources (accessed 2026-08-03):
  kimini   = kimini.online/blog/archives/84174 (準2級熟語まとめ, 参考: でる順パス単)
  best     = best-teacher-inc.com/blog/eikenpre2-vocabulary-list (過去問3年分析)
  aeon     = aeonet.co.jp/column/post_27.html (過去問出題熟語, 例文つき)
  qq       = qqeng.com/qqkids/english-column/kids20260211 (準2級頻出30選)
  ankA     = ankilot.com/view?id=hZAzjmyPxx (準2級重要熟語27)
  ankG2    = ankilot.com/view?id=jG1KKTIMpv (英検2級までの熟語 ~140)
  cheer    = english.cheerup.jp/article/8035 (準2級熟語練習問題)
  jump     = jumpstartenglish.education/column/81 (準2級群動詞)
  stud     = studychain.jp/media/eiken-two-long-word (2級頻出, 補強)
  yt       = YouTube聞き流し25問+850 (補強)
tier: A=複数ソース/過去問確認 B=1-2ソース C=補強(2級重複含む)
"""
import json, os

# (en, ja, ex, cat, tier, [src])
RAW = [
# ---- GO ----
("go out","外出する；（食事に）出かける","We went out for dinner last night.","go","A",["kimini","ankG2"]),
("go over","～を詳しく調べる","Let's go over the plan again.","go","A",["kimini","ankG2"]),
("go on","続ける；起こる","Please go on reading the book.","go","A",["ankG2","yt"]),
("go ahead","どんどん進む；始める","You can go ahead and eat.","go","B",["ankG2"]),
("go by","（時が）経過する","Time goes by fast.","go","B",["ankG2"]),
("go off","（警報・爆弾が）鳴る、爆発する","The alarm went off at six.","go","B",["ankG2"]),
("go into","～に入る；（職業に）就く","He went into the room.","go","B",["ankG2","stud"]),
("go through","～を経験する；通過する","She went through a hard time.","go","B",["ankG2"]),
("go wrong","失敗する；調子が悪い","Don't worry, nothing will go wrong.","go","A",["aeon","qq"]),
("go for a walk","散歩に行く","My grandfather goes for a walk every morning.","go","B",["yt"]),
("go on a tour","ツアーに行く","They went on a tour of Kyoto.","go","B",["kimini"]),
# ---- COME ----
("come across","～に偶然出会う","I came across an old photo.","come","A",["ankG2","yt"]),
("come from","～の出身である","She comes from Canada.","come","B",["ankG2"]),
("come up with","～を思いつく","I can't come up with any ideas right now.","come","A",["aeon","ankG2"]),
("come out","（ニュースなどが）明らかになる","The truth finally came out.","come","B",["ankG2"]),
("come about","起こる","How did this come about?","come","C",["ankG2"]),
("come to do","～するようになる","I came to like English.","come","B",["ankG2","yt"]),
("come true","（夢などが）実現する","Her dream came true.","come","A",["ankG2"]),
("come to an end","終わる","The festival came to an end.","come","B",["ankG2"]),
("come back","戻ってくる","Come back soon!","come","B",["ankG2"]),
("come down with","～（病気）にかかる","He came down with a cold.","come","C",["cheer"]),
# ---- TAKE ----
("take advantage of","～を利用する","You should take advantage of the opportunity.","take","A",["best","ankG2"]),
("take in","～を理解する；受け入れる","The store takes in returns for up to 30 days.","take","A",["aeon","ankG2"]),
("take A for B","AをBだと思い込む","I took him for his brother.","take","B",["ankG2"]),
("take over","～を引き継ぐ","She took over the company.","take","B",["ankG2"]),
("take the place of","～の代わりをする","Nothing can take the place of water.","take","B",["ankG2"]),
("take it easy","楽にやる、のんびりする","Take it easy today.","take","A",["qq","ankG2"]),
("take A for granted","～を当然のことと思う","Don't take your family for granted.","take","B",["ankG2"]),
("take place","行われる、起こる","The fireworks celebration will take place on Monday.","take","A",["aeon","ankG2","cheer"]),
("take one's time","ゆっくりやる","Take your time. There's no hurry.","take","B",["ankG2"]),
("take a look at","～を見る","Take a look at this picture.","take","B",["ankG2"]),
("take up","（場所・時間を）占める；始める","This desk takes up too much space.","take","B",["ankG2"]),
("take care of","～の世話をする；処理する","I'll take care of the paperwork for you.","take","A",["aeon","kimini","ankG2"]),
("take part in","～に参加する","He took part in the basketball club.","take","A",["best","ankG2"]),
("take off","（服を）脱ぐ；（飛行機が）離陸する","Please take off your shoes.","take","A",["ankG2","jump"]),
("take pride in","～を誇りに思う","We take pride in our school.","take","B",["ankG2"]),
("take away","～を持ち去る","Please take away the trash.","take","B",["ankG2"]),
("take a break","休憩する","Let's take a break now.","take","A",["qq"]),
("take action","行動を起こす","She took action immediately.","take","A",["kimini","cheer"]),
("take a seat","座る","Please take a seat.","take","A",["kimini"]),
("take turns","交代でする","We took turns driving.","take","B",["ankG2"]),
("take notes","メモを取る","She takes notes in every class.","take","B",["ankG2"]),
# ---- BRING ----
("bring in","（賃金・金額を）稼ぐ","The shop brings in a lot of money.","bring","B",["ankG2"]),
("bring up","（子供を）育てる","She brought up three children.","bring","A",["ankG2","yt"]),
("bring back","～を戻す、持ち帰る","Please bring back my book.","bring","A",["kimini","ankG2"]),
("bring out","～をはっきり出す","The salt brings out the flavor.","bring","B",["ankG2"]),
("bring oneself to do","～する気になる","I couldn't bring myself to tell her.","bring","C",["ankG2"]),
("bring about","～を引き起こす","The new law brought about big changes.","bring","B",["ankG2"]),
("bring A to life","Aを生き返らせる","The story brings history to life.","bring","C",["ankG2"]),
("bring A to an end","Aを終わらせる","We brought the meeting to an end.","bring","C",["ankG2"]),
# ---- GIVE ----
("give up","あきらめる","Never give up!","give","A",["ankG2","jump"]),
("give away","～をただで与える","She gave away her old clothes.","give","B",["ankG2"]),
("give out","～を配る","The teacher gave out the test papers.","give","B",["ankG2"]),
("give in","屈する、降参する","He finally gave in.","give","B",["ankG2"]),
("give A a hand","Aを手伝う","Can you give me a hand?","give","A",["ankG2"]),
("give rise to","～を引き起こす","The accident gave rise to many problems.","give","C",["ankG2"]),
("give birth to","～を産む","She gave birth to a baby girl.","give","B",["ankG2"]),
("give off","（におい・光を）発する","The flowers were giving off a sweet fragrance.","give","A",["aeon","ankG2"]),
("give A a ride","Aを車に乗せる","My father gave me a ride to school.","give","B",["kimini"]),
# ---- GET ----
("get to","～に到着する","How can I get to the station?","get","A",["ankG2"]),
("get along with","～と仲良くやっていく","I get along with my classmates.","get","A",["ankG2","cheer"]),
("get on","（バス・電車に）乗る","We got on the bus.","get","A",["kimini","ankG2"]),
("get off","（バス・電車から）降りる","I get off at the next station.","get","A",["kimini","ankG2"]),
("get in","～に入る、乗り込む","Get in the car.","get","A",["kimini","best"]),
("get out","～から出る","Get out of the room.","get","B",["kimini"]),
("get rid of","～を処分する","We should get rid of that old carpet.","get","A",["cheer","ankG2"]),
("get through","～を切り抜ける","We got through the hard winter.","get","B",["ankG2"]),
("get over","～から立ち直る","She got over her illness.","get","B",["ankG2"]),
("get lost","道に迷う","I got lost in the city.","get","A",["ankG2"]),
("get ready for","～の準備をする","Get ready for school.","get","A",["kimini"]),
("get in shape","体を鍛える、体調を整える","I want to get in shape.","get","B",["qq"]),
("get up","起きる","I get up at six every day.","get","A",["jump"]),
("get back","戻ってくる","She got back home late.","get","B",["ankG2"]),
("get together","集まる","Let's get together next week.","get","B",["ankG2"]),
# ---- HAVE ----
("have on","（服を）身に着けている","She had a red hat on.","have","B",["ankG2"]),
("have access to","～を利用できる","Students have access to the library.","have","B",["ankG2"]),
("have no idea","全く分からない","I have no idea.","have","A",["ankG2","yt"]),
("have A in common","Aを共通に持つ","We have a lot in common.","have","A",["ankG2","kimini"]),
("have a good time","楽しい時を過ごす","We had a good time at the party.","have","A",["ankG2"]),
("have nothing to do with","～と関係がない","It has nothing to do with me.","have","B",["ankG2"]),
("have something to do with","～と関係がある","This has something to do with him.","have","B",["ankG2"]),
("have A do","Aに～させる","My mother had me wash the dishes.","have","B",["ankG2"]),
("have a sore throat","のどが痛む","I have a sore throat.","have","A",["kimini"]),
("have trouble with","～で困っている","She's having trouble with her computer.","have","A",["aeon"]),
# ---- KEEP ----
("keep A from doing","Aが～するのを防ぐ","The rain kept us from going out.","keep","B",["ankG2"]),
("keep track of","～を見失わないようにする","Keep track of your money.","keep","C",["ankG2"]),
("keep up with","～についていく","It's hard to keep up with all the latest technology trends.","keep","A",["aeon","kimini","ankG2"]),
("keep on","～し続ける","He kept on working.","keep","A",["kimini","ankG2"]),
("keep A in mind","～を覚えておく","Keep this rule in mind.","keep","A",["qq","ankG2"]),
("keep in touch with","～と連絡を取り合う","I keep in touch with my old friends.","keep","B",["ankG2"]),
("keep pace with","～に遅れないようについていく","Keep pace with the times.","keep","C",["ankG2"]),
("keep out","～を入れない","Keep out of this room.","keep","B",["ankG2"]),
("keep from","～を差し控える","I couldn't keep from laughing.","keep","C",["ankG2"]),
("keep to","～から外れないでいる","Keep to the left.","keep","C",["ankG2"]),
("keep away","近づかない","Keep away from the fire.","keep","B",["ankG2"]),
("keep A to oneself","～を秘密にしておく","Keep this secret to yourself.","keep","B",["ankG2"]),
# ---- HOLD ----
("hold on","電話を切らないで待つ；持ちこたえる","Hold on a second.","hold","A",["kimini","best"]),
("hold up","～を支える","The pillars hold up the roof.","hold","B",["ankG2"]),
("hold back","～を引き止める；抑える","She held back her tears.","hold","B",["ankG2"]),
("hold down","（価格などを）抑制する","We must hold down costs.","hold","C",["ankG2"]),
("hold one's breath","息を止める","I held my breath and waited.","hold","B",["yt"]),
# ---- PUT ----
("put on","～を着用する","Put on your coat.","put","A",["kimini","qq","ankG2"]),
("put together","～をまとめる","She put together a great plan.","put","B",["ankG2"]),
("put forward","（意見を）提案する","He put forward a new idea.","put","B",["ankG2"]),
("put down","～を書き留める","Put down your name.","put","B",["ankG2"]),
("put up with","～を我慢する","I cannot put up with this noise.","put","A",["best","ankG2"]),
("put an end to","～を終わらせる","We must put an end to this.","put","B",["ankG2"]),
("put A into B","AをB（他国語）に翻訳する","Put this sentence into Japanese.","put","B",["ankG2"]),
("put off","～を延期する","The rain put off the soccer tournament.","put","A",["best","ankG2"]),
("put away","～を片付ける","Put away your books.","put","A",["aeon","ankG2"]),
("put out","（火を）消す","The firefighters put out the fire.","put","A",["ankG2","yt"]),
("put up","～を掲示する；泊める","We put up a tent.","put","B",["ankG2"]),
# ---- SET ----
("set up","～を設立する","They set up a new company.","set","A",["kimini","ankG2"]),
("set aside","（金・時間を）取っておく","I set aside some money every month.","set","B",["ankG2"]),
("set out","出発する","We set out early in the morning.","set","B",["ankG2"]),
("set in","（好ましくないことが）始まる","Winter has set in.","set","C",["ankG2"]),
("set off","～を引き起こす；出発する","The noise set off the alarm.","set","B",["ankG2"]),
("set A free","Aを自由にする","They set the bird free.","set","B",["ankG2"]),
# ---- MAKE ----
("make sense","道理にかなう、意味が通じる","Your answer makes sense.","make","A",["kimini","ankG2"]),
("make a difference","重要である、違いを生む","Your help makes a big difference.","make","B",["ankG2"]),
("make one's way","進む","We made our way through the crowd.","make","B",["ankG2"]),
("make a living","生計を立てる","He makes a living as a musician.","make","A",["aeon","ankG2"]),
("make use of","～を利用する","Make use of the library.","make","A",["best","ankA"]),
("make fun of","～をからかう","Don't make fun of others.","make","A",["best","ankA"]),
("make sense of","～を理解する","I can't make sense of this poem.","make","B",["best"]),
("make out","～を理解する；見分ける","I'm trying to make out how to solve this puzzle.","make","A",["aeon","best"]),
("make up one's mind","決心する","She made up her mind to study abroad.","make","A",["kimini","yt"]),
("make up for","～を埋め合わせる","He worked hard to make up for lost time.","make","B",["kimini"]),
("make a mistake","間違いを犯す","Don't worry if you make a mistake.","make","A",["aeon"]),
("make a reservation","予約をする","I'd like to make a reservation for two.","make","A",["aeon"]),
("make money","お金を稼ぐ","She makes money by freelancing.","make","A",["aeon","yt"]),
("make progress","進歩する","You are making good progress.","make","A",["aeon","yt"]),
("make an appointment with","～と約束をする","I made an appointment with the doctor.","make","A",["kimini"]),
("make an effort","努力する","Make an effort to be on time.","make","B",["yt"]),
("make it","なんとか間に合う","We made it just in time.","make","B",["stud"]),
("make the most of","～を最大限に利用する","Make the most of your free time.","make","B",["yt"]),
# ---- LOOK ----
("look after","～の世話をする","I have to look after my little brother.","look","A",["kimini","qq","ankG2"]),
("look at","～を見る","Look at the blackboard.","look","A",["kimini"]),
("look for","～を探す","I'm looking for my keys.","look","A",["kimini"]),
("look out","用心する","Look out! A car is coming.","look","A",["kimini"]),
("look over","～に目を通す","Please look over my report.","look","A",["kimini"]),
("look through","～をざっと調べる","I looked through the magazine.","look","A",["kimini"]),
("look forward to","～を楽しみにしている","I'm looking forward to meeting you next week.","look","A",["aeon","jump"]),
("look up","（単語などを）調べる","Can you look up the meaning of this word?","look","A",["aeon"]),
("look up to","～を尊敬する","He looks up to his boss.","look","B",["best","yt"]),
("look down on","～を見下す","Don't look down on others.","look","B",["yt"]),
("look into","～を調べる","The police looked into the matter.","look","B",["yt"]),
("look like","～のように見える","It looks like rain.","look","B",["kimini"]),
# ---- BE phrases ----
("be aware of","～に気づいている","The dog is aware of me.","be","A",["best","kimini"]),
("be sure to do","必ず～する","Be sure to lock the door.","be","A",["best","ankA"]),
("be used to doing","～するのに慣れている","He is used to running a long distance.","be","A",["best","kimini"]),
("be no use doing","～しても無駄である","It is no use crying.","be","B",["best"]),
("be willing to do","進んで～する","She is willing to clean her room.","be","A",["best"]),
("be interested in","～に興味がある","She is interested in learning Japanese.","be","A",["aeon","qq"]),
("be made up of","～で構成される","The committee is made up of experts.","be","A",["aeon"]),
("be good at","～が得意である","He is good at playing soccer.","be","A",["qq"]),
("be poor at","～が苦手である","I am poor at math.","be","A",["kimini"]),
("be afraid of","～を怖がる","She is afraid of dogs.","be","A",["qq"]),
("be full of","～でいっぱいである","The box is full of toys.","be","A",["qq","yt"]),
("be sick of","～に飽き飽きする","I'm sick of this weather.","be","B",["qq"]),
("be tired of","～にうんざりしている","She is tired of his lies.","be","A",["kimini","yt"]),
("be tired from","～で疲れている","I'm tired from the long walk.","be","A",["kimini"]),
("be ready for","～の用意ができている","Are you ready for the test?","be","A",["qq"]),
("be popular with","～に人気がある","This game is popular with students.","be","A",["kimini"]),
("be grateful for","～に感謝している","I'm grateful for your help.","be","A",["kimini"]),
("be out of the question","問題外である","Lying is out of the question.","be","A",["kimini","aeon"]),
("be unable to do","～することができない","He was unable to answer.","be","A",["kimini"]),
("be expected to do","～するよう期待される","You are expected to be on time.","be","A",["kimini"]),
("be about to do","～しようとしているところだ","I was just about to clean my room.","be","A",["cheer"]),
("be supposed to do","～することになっている","You are supposed to wear a uniform.","be","B",["ankG2"]),
("be familiar with","～によく知っている","Are you familiar with this area?","be","B",["yt"]),
("be proud of","～を誇りに思う","I'm proud of you.","be","B",["ankG2"]),
("be rich in","～に富んでいる","This area is rich in nature.","be","B",["yt"]),
("be short of","～が不足している","We are short of water.","be","B",["yt"]),
("be free to do","自由に～してよい","You are free to ask questions.","be","B",["yt"]),
("be connected with","～と関係がある","This case is connected with the accident.","be","B",["yt"]),
("be in charge of","～を担当している","Who is in charge of this class?","be","A",["best","kimini"]),
("be free from","～がない","This drink is free from sugar.","be","C",["yt"]),
("be to blame for","～の責任がある","He is to blame for the mistake.","be","C",["yt"]),
# ---- Verb + preposition ----
("depend on","～次第である；頼る","The price depends on the size.","verb","A",["aeon","best"]),
("rely on","～を信頼する、頼る","You can rely on me.","verb","A",["kimini","jump"]),
("belong to","～に属する","This book belongs to me.","verb","A",["aeon"]),
("participate in","～に参加する","Many students participated in the event.","verb","A",["qq","jump"]),
("focus on","～に集中する","Focus on your homework.","verb","A",["qq","yt"]),
("pay attention to","～に注意する","Pay attention to the teacher.","verb","A",["kimini","qq"]),
("pay for","～の費用を払う","I'll pay for the tickets.","verb","A",["kimini","yt"]),
("wait for","～を待つ","I waited for the bus.","verb","A",["stud"]),
("care about","～に関心がある","She cares about the environment.","verb","A",["qq"]),
("worry about","～について心配する","Don't worry about the test.","verb","A",["qq"]),
("wonder about","～について知りたいと思う","I wonder about the future.","verb","B",["qq"]),
("think of","考える；思い出す","I can't think of his name right now.","verb","A",["aeon"]),
("hear from","～から便りがある","I heard from my pen pal.","verb","B",["yt"]),
("suffer from","～に苦しむ","Her grandfather suffers from backache.","verb","A",["cheer"]),
("graduate from","～を卒業する","She graduated from high school.","verb","A",["kimini"]),
("consist of","～からなる","The team consists of ten players.","verb","B",["yt"]),
("agree with","～に同意する","I agree with your opinion.","verb","B",["yt"]),
("deal with","～に対処する","I will deal with the issue.","verb","B",["best","yt"]),
("do without","～なしで済ます","My sister cannot do without her smartphone.","verb","A",["kimini","cheer"]),
("do away with","～を廃止する","The school did away with the rule.","verb","C",["yt"]),
("add to","～に付け加える","The music added to our joy.","verb","B",["qq"]),
("ask for","～を頼む","He asked for help.","verb","B",["qq"]),
("run after","～を追いかける","The dog ran after the ball.","verb","A",["kimini"]),
("run out of","～を使い果たす","We ran out of milk.","verb","A",["qq","yt"]),
("run over","～をひく","The car ran over a cat.","verb","B",["kimini"]),
("run into","～に偶然会う","I ran into my teacher at the mall.","verb","B",["cheer"]),
("search for","～を探す","They searched for the missing boy.","verb","B",["kimini"]),
("stand by","～を支援する","We will stand by you.","verb","B",["kimini","yt"]),
("stand out","目立つ","Her red dress stood out.","verb","B",["yt"]),
("stay up late","夜更かしする","Don't stay up late.","verb","B",["yt"]),
("show off","～を見せびらかす","He likes to show off his new bike.","verb","A",["kimini","yt"]),
("sign up","申し込む","I signed up for the class.","verb","B",["stud"]),
("speak up","大きな声で話す","Please speak up.","verb","B",["yt"]),
("turn down","～を断る；（音量を）下げる","He turned down the offer.","verb","A",["kimini","yt"]),
("turn into","～に変わる","The rain turned into snow.","verb","A",["kimini","yt"]),
("turn to","～に助けを求める","She turned to her friends.","verb","B",["kimini"]),
("turn out","結局～であることがわかる","The story turned out to be true.","verb","B",["cheer"]),
("turn up","姿を現す","He turned up late.","verb","B",["cheer"]),
("try on","～を試着する","Can I try on this shirt?","verb","A",["stud","yt"]),
("watch out for","～に気をつける","Watch out for cars.","verb","A",["kimini"]),
("work out","解決する；運動する","Everything will work out.","verb","B",["ankG2"]),
("cut down on","～を切り詰める","Cut down on sugar.","verb","B",["yt"]),
("cut off","～を切り離す","They cut off the relationship.","verb","C",["best"]),
("call off","～を中止する","They called off the game.","verb","B",["jump"]),
("call on","～を訪問する","I called on my aunt.","verb","B",["ankG2"]),
("call back","折り返し電話する","I'll call you back later.","verb","B",["stud"]),
("carry on","続ける","Carry on with your work.","verb","B",["jump"]),
("carry out","実行する","He carried out his task.","verb","B",["best"]),
("catch up with","～に追いつく","We can catch up with the others after lunch.","verb","A",["kimini","cheer"]),
("catch a cold","風邪をひく","I caught a cold yesterday.","verb","B",["ankG2"]),
("check out","チェックアウトする","We checked out of the hotel at ten.","verb","A",["kimini"]),
("cheer up","元気づける","Cheer up! Everything will be fine.","verb","B",["jump"]),
("calm down","落ち着く","Calm down and tell me what happened.","verb","B",["jump"]),
("break down","故障する","My car broke down.","verb","B",["jump"]),
("dress up","着飾る","The children dressed up for Halloween.","verb","B",["jump"]),
("drop by","～に立ち寄る","Drop by my house anytime.","verb","A",["kimini"]),
("stop by","～に立ち寄る","I'll stop by the store.","verb","A",["kimini"]),
("eat out","外食する","Why don't we eat out tonight?","verb","A",["aeon"]),
("end up","結局～になる","We ended up staying home.","verb","B",["yt"]),
("figure out","理解する、解決する","I need some time to figure out this problem.","verb","A",["aeon","yt"]),
("find out","調べる、発見する","I'm trying to find out more about the history of this city.","verb","A",["aeon","best"]),
("find fault with","～に文句を言う","My boss is always finding fault with my work.","verb","B",["aeon"]),
("hand in","～を提出する","Hand in your homework.","verb","A",["qq","jump"]),
("hand over","～を引き渡す","Please hand over the documents.","verb","A",["aeon"]),
("hang up","電話を切る","She hung up the phone.","verb","B",["yt"]),
("head for","～に向かう","We headed for the station.","verb","B",["cheer"]),
("let down","～を失望させる","Don't let your friends down.","verb","B",["kimini"]),
("line up","列を作る","The students lined up.","verb","B",["kimini"]),
("lose weight","痩せる","She wants to lose weight.","verb","A",["qq"]),
("pick up","～を拾い上げる；迎えに行く","I'll pick you up at seven.","verb","A",["kimini","stud"]),
("point out","指摘する","The teacher pointed out my mistake.","verb","A",["qq","cheer"]),
("name A after B","BにちなんでAを名付ける","They named the dog after their grandfather.","verb","B",["kimini"]),
("believe in","～を信じる","I believe in you.","verb","B",["yt"]),
("provide A with B","AにBを与える","The school provides students with lunch.","verb","B",["yt"]),
("prevent A from doing","Aが～するのを防ぐ","The rain prevented us from playing.","verb","B",["yt"]),
("tell A from B","AとBを見分ける","It's hard to tell the twins apart, but I can tell Ken from his brother.","verb","C",["yt"]),
("remind A of B","AにBを思い出させる","This song reminds me of summer.","verb","B",["yt"]),
("play an important role in","～で重要な役割を果たす","Volunteers play an important role in this event.","verb","A",["kimini","yt"]),
("fall in love with","～と恋に落ちる","She fell in love with the city.","verb","B",["qq"]),
("feel at home","くつろいだ気分になる","Please feel at home.","verb","B",["qq"]),
("do the laundry","洗濯する","My father does the laundry.","verb","B",["qq"]),
("do A a favor","Aの願いを聞く","Can you do me a favor?","verb","A",["kimini","yt"]),
# ---- Prepositional / adverbial phrases ----
("(just) in case","万一に備えて","Take an umbrella just in case.","prep","A",["kimini"]),
("a bunch of","一束の～","She bought a bunch of flowers.","prep","B",["kimini"]),
("as a result of","～の結果として","The game was canceled as a result of the rain.","prep","A",["kimini"]),
("as a result","その結果として","He studied hard. As a result, he passed.","prep","B",["yt"]),
("at least","少なくとも","You should at least order a drink.","prep","A",["kimini","aeon"]),
("at most","多くても","It will take at most two hours.","prep","B",["kimini"]),
("at a time","一度に","Don't eat three apples at a time.","prep","B",["qq"]),
("at the moment","今、現在","He is busy at the moment.","prep","B",["qq"]),
("at the same time","同時に","She was happy and sad at the same time.","prep","A",["aeon"]),
("at last","ついに","At last, the bus came.","prep","B",["yt"]),
("at one time","かつて；一度に","At one time, I lived in Osaka.","prep","B",["yt"]),
("at random","でたらめに","Pick a card at random.","prep","B",["yt"]),
("at first","最初は","At first, I didn't like it.","prep","B",["cheer"]),
("by chance","偶然に","I met my neighbor by chance.","prep","A",["kimini","best"]),
("by accident","偶然に","I heard about it by accident.","prep","A",["cheer"]),
("by any chance","ひょっとして","By any chance, do you have a spare pen?","prep","A",["aeon"]),
("by heart","暗記して","He can play the song by heart.","prep","A",["aeon"]),
("by mistake","間違って","I took your umbrella by mistake.","prep","B",["yt"]),
("by now","今頃にはもう","She should be home by now.","prep","B",["yt"]),
("by way of","～経由で","We went to Kyoto by way of Nagoya.","prep","C",["yt"]),
("by the time","～するまでには","By the time I arrived, the movie had started.","prep","B",["kimini"]),
("day by day","日に日に","Her English is getting better day by day.","prep","B",["yt"]),
("step by step","一歩ずつ","Learn it step by step.","prep","B",["yt"]),
("little by little","少しずつ","Little by little, the snow melted.","prep","B",["yt"]),
("except for","～を除いては","Everyone was there except for Ken.","prep","A",["kimini"]),
("from now on","今後は","From now on, I'll study harder.","prep","A",["kimini"]),
("from time to time","時々","I see him from time to time.","prep","B",["yt"]),
("in addition to","～に加えて","In addition to English, she speaks French fluently.","prep","A",["kimini","aeon"]),
("in common","共通して","Dawn and her boyfriend have a lot in common.","prep","A",["kimini","cheer"]),
("in line","一直線に、整列して","Stand in line, please.","prep","A",["kimini"]),
("in particular","特に","I love fruits, in particular apples.","prep","A",["kimini"]),
("in advance","前もって","Please pay the fee in advance.","prep","A",["aeon"]),
("in spite of","～にもかかわらず","In spite of bad weather, the game started.","prep","A",["best"]),
("instead of","～の代わりに","I'll cook instead of you.","prep","A",["best"]),
("in a minute","すぐに","I'll be back in a minute.","prep","A",["kimini","cheer"]),
("in charge of","～を担当して","Who is in charge of this project?","prep","A",["best"]),
("in the middle of","～の途中で","Don't talk in the middle of class.","prep","B",["stud"]),
("in the future","将来","I want to be a doctor in the future.","prep","B",["stud"]),
("in detail","詳しく","Tell me about it in detail.","prep","B",["yt"]),
("in general","一般的に","In general, dogs are friendly.","prep","B",["yt"]),
("in reality","実際には","In reality, it was not easy.","prep","B",["yt"]),
("in place of","～の代わりに","Use honey in place of sugar.","prep","B",["yt"]),
("in turn","順番に","Each student spoke in turn.","prep","C",["cheer"]),
("in contrast","対照的に","In contrast, his sister is quiet.","prep","C",["cheer"]),
("out of order","故障して","The elevator is out of order.","prep","B",["cheer"]),
("out of date","時代遅れの","This phone is out of date.","prep","A",["kimini","yt"]),
("out of control","制御できない","The fire got out of control.","prep","B",["yt"]),
("out of sight","見えないところに","The ship went out of sight.","prep","B",["yt"]),
("on purpose","わざと","Did you break the vase on purpose?","prep","A",["aeon"]),
("on business","仕事で","My father went to Tokyo on business.","prep","A",["kimini"]),
("on one's own","自分自身で","She did it on her own.","prep","A",["kimini"]),
("on duty","当直で","The nurse is on duty today.","prep","B",["stud"]),
("on foot","徒歩で","We went to school on foot.","prep","B",["yt"]),
("on behalf of","～を代表して","I'm writing on behalf of my team.","prep","C",["stud"]),
("on average","平均して","On average, I sleep seven hours.","prep","B",["yt"]),
("on the point of","～しようとしていたところ","They were on the point of leaving when the phone rang.","prep","B",["aeon"]),
("on the way home","帰り道に","I bought some bread on the way home.","prep","B",["yt"]),
("once a week","週に1度","I play tennis once a week.","prep","B",["kimini"]),
("no longer","もはや～でない","He no longer lives here.","prep","A",["kimini"]),
("no doubt","疑いなく","No doubt she will win.","prep","B",["yt"]),
("nothing but","ただ～だけ","He eats nothing but ramen.","prep","B",["yt"]),
("more and more","ますます","More and more people are starting to work remotely.","prep","A",["aeon"]),
("so far","今までのところ","Do you have any questions so far?","prep","A",["kimini","aeon","best"]),
("as usual","いつものように","Ken was late for work as usual.","prep","A",["aeon"]),
("as well","～もまた","I think everyone else did as well.","prep","A",["aeon"]),
("as well as","～だけでなく","B as well as A = AだけでなくBも","prep","B",["yt"]),
("as for","～については","As for me, I'll stay home.","prep","B",["yt"]),
("as if","まるで～かのように","He talks as if he knew everything.","prep","B",["cheer"]),
("according to","～によれば","According to the map, we should turn left.","prep","A",["cheer"]),
("around the world","世界中で","This product is famous around the world.","prep","A",["aeon"]),
("all of a sudden","突然","He left the room all of a sudden.","prep","A",["aeon"]),
("a couple of","2、3の～","I'll be there in a couple of minutes.","prep","B",["qq"]),
("a sheet of","1枚の～","Give me a sheet of paper.","prep","B",["qq"]),
("a number of","多くの～","A number of students joined the club.","prep","B",["kimini"]),
("a variety of","様々な～","There is a variety of fruits at the market.","prep","A",["aeon"]),
("plenty of","たくさんの～","We have plenty of time.","prep","A",["kimini"]),
("thanks to","～のおかげで","Thanks to your help, I passed.","prep","B",["stud"]),
("due to","～のせいで","The festival was canceled due to rain.","prep","B",["best"]),
("because of","～のせいで","The game was canceled because of the rain.","prep","B",["yt"]),
("the other day","先日","I saw her the other day.","prep","B",["yt"]),
("right away","すぐに","I'll do it right away.","prep","B",["yt"]),
("face to face","面と向かって","Let's talk face to face.","prep","B",["yt"]),
("what's worse","さらに悪いことに","What's worse, it started to rain.","prep","C",["yt"]),
("to begin with","そもそも；まず第一に","To begin with, I don't agree.","prep","B",["yt"]),
("to tell the truth","実を言うと","To tell the truth, I forgot.","prep","B",["yt"]),
("for instance","例えば","Last month, for instance, the sales went up.","prep","A",["aeon"]),
("for a while","しばらくの間","I lived there for a while.","prep","B",["stud"]),
("with luck","運が良ければ","With luck, we'll finish today.","prep","B",["kimini"]),
("after all","結局","After all, he didn't come.","prep","B",["yt"]),
("never A without doing","Aすると必ず～する","I never see her without thinking of my sister.","prep","C",["yt"]),
("prefer A to B","BよりAを好む","I prefer tea to coffee.","prep","A",["kimini"]),
("used to do","以前はよく～した","I used to play baseball.","prep","A",["kimini"]),
("come to mind","心に浮かぶ","A good idea came to mind.","prep","B",["qq"]),
# ---- Conversation expressions ----
("Why don't you","～しませんか？","Why don't you come with us?","conv","A",["best"]),
("Would you like","～はいかがですか？","Would you like some tea?","conv","A",["best"]),
("How about","～はどうですか？","How about going swimming?","conv","A",["best"]),
("Do you mind if","～してもいいですか？","Do you mind if I open the window?","conv","A",["best"]),
("Would you mind -ing","～していただけませんか？","Would you mind carrying this box?","conv","A",["best"]),
("make yourself at home","どうぞくつろいでください","Please make yourself at home.","conv","A",["best"]),
("help yourself to","どうぞご自由に～を食べてください","Please help yourself to some cake.","conv","A",["best"]),
("What do you say to -ing","～しませんか？","What do you say to eating out tonight?","conv","B",["best"]),
]

def main():
    items = []
    seen = {}
    for i, (en, ja, ex, cat, tier, src) in enumerate(RAW, 1):
        key = en.lower()
        if key in seen:
            print(f"DUPLICATE: {en} (first id={seen[key]})")
            continue
        seen[key] = f"idiom-{i:04d}"
        items.append({
            "id": f"idiom-{i:04d}",
            "en": en,
            "ja": ja,
            "ex": ex,
            "cat": cat,
            "tier": tier,
            "src": src,
        })
    out = {
        "version": 1,
        "grade": "eiken-pre2",
        "title": "英検準2級 頻出熟語",
        "note": "複数Webソース（準2級過去問分析・でる順パス単準拠リスト等）を突合して作成。tier A=高頻出 B=中頻出 C=補強(2級重複含む)。",
        "items": items,
    }
    dst = os.path.join(os.path.dirname(__file__), "..", "data", "idioms_pre2.json")
    with open(dst, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
    from collections import Counter
    tiers = Counter(it["tier"] for it in items)
    cats = Counter(it["cat"] for it in items)
    print(f"total={len(items)} tiers={dict(tiers)} cats={dict(cats)}")
    print(f"written: {os.path.abspath(dst)}")

if __name__ == "__main__":
    main()
